on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

  workflow_dispatch:
    inputs:
      build:
        description: Unit tests
        type: boolean
        required: true
        default: "true"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm i gulp gulp-cli -g
      if: runner.os == 'MacOS'
    - run: gulp package
    - run: gulp install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
