name: Compute and Use Value

on:
  push:
    branches:
      - main

jobs:
  compute-value:
    runs-on: ubuntu-latest
    steps:
      - name: Compute Value
        id: compute
        run: |
          # Compute the value (for example, let's say it's a hash of the commit)
          COMPUTED_VALUE=$(echo "${{ github.sha }}" | sha256sum | cut -d ' ' -f1)
          echo "Computed value: $COMPUTED_VALUE"
          echo "::set-env name=MY_ENV_VAR::$COMPUTED_VALUE"

  use-value:
    needs: compute-value
    runs-on: ubuntu-latest
    steps:
      - name: Use Computed Value
        run: |
          # Access the computed value from the first job
          echo "Using value from environment variable: $MY_ENV_VAR"
